services:
    main.app.form.type.car:
        class: main\AppBundle\Form\Type\CarType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    main.app.google_locator:
        class: main\AppBundle\Services\GooglePlaceLocator
        arguments: ['%key_google%']
        tags:
            - { name: place_locator }
    main.app.here_locator:
        class: main\AppBundle\Services\HerePlaceLocator
        arguments: ['%here_api_id%','%here_app_code%']
        tags:
            - { name: place_locator }
    main.app.chained_locator:
        class: main\AppBundle\Services\ChainedPlaceLocator
        tags:
                    - { name: place_locator_chain }