<?php

namespace main\AppBundle\Repository;
use main\AppBundle\Entity\Tagg;

/**
 * TaggRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaggRepository extends \Doctrine\ORM\EntityRepository
{

        public function persistAndFlush (Tagg $tag)
        {
            $this->_em->persist($tag);
            $this->_em->flush();
        }
}
